[FIX] pos_self_order: translate custom link names for available languages
Steps to reproduce:
-------------------
1. Enable self ordering with default language set to French
2. Open the self-order interface

-> The "Order Now" button label is still in English.

Why the issue:
--------------
The "Order Now" link is created dynamically in Python, so its translations
are not automatically populated from the po files. Only the language active
at creation time (typically English) is stored.

The fix:
--------
In `_prepare_self_order_custom_btn`, after finding or creating that link,
populate the translations for it, for all available self-ordering
languages, using `get_translation`. We skip updating the translation if
it's already different from the source (in that case, it's probably
customized by the user).

Notes:
------
`get_translation` was directly used because we cannot use `env._`
function as follows: `env._(link.name)` as that will throw a linting
error: "Bad usage of _, _lt function. (E8502)".

See: https://www.odoo.com/documentation/master/developer/howtos/translations.html#variables

opw-6088248